# Generated by Django 5.1.3 on 2024-11-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('post_text', models.TextField(verbose_name='Текст поста')),
                ('post_image', models.ImageField(blank=True, upload_to='images/post/', verbose_name='Изображение поста')),
                ('post_image_url', models.ImageField(blank=True, upload_to='', verbose_name='URL изображения поста')),
                ('post_time', models.DateTimeField(verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_dislike', models.ManyToManyField(blank=True, related_name='post_disliked', to=settings.AUTH_USER_MODEL)),
                ('post_like', models.ManyToManyField(blank=True, related_name='post_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
